import type { CriterionId, StoryKind } from './types'
import type { Decision } from './lib/score'

export type Locale = 'ja' | 'en'

export function detectLocale(): Locale {
  return typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('ja') ? 'ja' : 'en'
}

export const COPY = {
  ja: {
    drop: 'PDF をドロップして追加', choose: 'ファイルを選択', limit: '1 ファイル 50 MB まで',
    settings: '設定', close: '閉じる', back: '一覧へ',
    states: { queued: '待機中', scanning: 'スキャン中', scanned: '未レビュー', reviewing: 'レビュー中', done: '完了', error: 'エラー' },
    errors: {
      AI_NOT_CONFIGURED: 'AI 未設定です。設定から接続先を選ぶと自動で再開します。',
      NEEDS_OCR: '画像のみの PDF です。設定で OCR 用の画像対応モデルを選ぶと再スキャンできます。',
      AI_NO_TEXT: '本文を読み取れませんでした。',
      OCR_FAILED: 'OCR に失敗しました。設定の OCR に画像入力対応モデルを選んで再試行してください。',
      AI_INVALID_RESPONSE: 'AI の応答を解釈できませんでした。再実行してください。',
      PDF_MISSING: 'PDF 本体が見つかりません。もう一度ドロップしてください。',
      PDF_READ_FAILED: 'PDF を読み込めません。破損やパスワード保護を確認してください。',
      PDF_INVALID: '有効な PDF ではありません。', PDF_TOO_LARGE: '50 MB を超えています。', PDF_STORAGE: 'ブラウザーに保存できませんでした。',
      VIEWER_FILE_MISSING: 'tc-pdf-viewer の PDF 本体を読み込めませんでした。tc-pdf-viewer で一度開いてから選び直してください。',
      UNKNOWN: '処理に失敗しました。',
    } as Record<string, string>,
    decisions: { 'strong-accept': 'Strong Accept', accept: 'Accept', borderline: 'Borderline', 'weak-reject': 'Weak Reject', reject: 'Reject' } as Record<Decision, string>,
    criteria: { soundness: '技術的妥当性', evidence: '実証の強さ', novelty: '新規性', significance: '重要性', clarity: '明瞭さ', reproducibility: '再現性' } as Record<CriterionId, string>,
    structureLabels: { abstract: '要旨', method: '手法', results: '実験・結果', limitations: '限界の議論', references: '参考文献', artifacts: 'コード/データ公開' } as Record<string, string>,
    caps: { unsound: '技術的妥当性が低いため上限 40', fatal: '致命的な欠陥があるため上限 45' },
    score: 'スコア', confidence: '信頼度', weight: '重み', evidence: '根拠', verified: '本文で確認', unverified: '本文に見当たらない',
    summary: '要約', strengths: '強み', weaknesses: '弱み', questions: '著者への質問', fatalFlaws: '致命的な欠陥', structure: '構成チェック',
    howScored: '算出方法', formula: '各観点 1–5 を根拠の確認率で中立 (3) 側へ補正 → 重み付き平均を 0–100 に換算 (90%) + 構成チェック (10%) → 致命的欠陥などで上限。',
    pages: (scan: { pages: number; scannedPages: number; ocrPages: number; truncated: boolean }) => `${scan.pages} ページ` + (scan.truncated ? `（先頭 ${scan.scannedPages} ページを評価）` : '') + (scan.ocrPages ? ` · OCR ${scan.ocrPages} ページ` : ''),
    startReview: 'レビューを開始', notReviewed: 'まだレビューしていません。理解モードだけで使うこともできます。', rerun: '再レビュー', retry: '再試行', open: 'PDF を開く', remove: '削除', confirmRemove: 'もう一度押すと削除', copyMd: 'Markdown をコピー', copied: 'コピーしました',
    duplicate: '登録済みの PDF です', aiSettings: 'AI 接続', aiNote: '「レビュー」と「OCR」に使うモデルを選べます。OCR には画像入力に対応したモデルが必要です。PDF 本文は選択した AI に送信されます。',
    steps: { scan: '本文スキャン', review: 'AI 査読', score: '採点' },
    progress: {
      queued: '順番待ちです（1 本ずつ処理します）',
      scan: (done?: number, total?: number) => total ? `ページ ${done}/${total} のテキストを抽出中` : 'PDF を開いています',
      ocr: (page?: number, total?: number) => `ページ ${page}/${total} を OCR 中（文字情報のないページ）`,
      send: (chars?: number) => `本文 ${(chars || 0).toLocaleString()} 文字を AI に送信し、応答を待っています`,
      generate: (chars?: number, field?: string) => `AI が査読を執筆中${field ? `: ${field}` : ''} · ${(chars || 0).toLocaleString()} 文字受信`,
      elapsed: (s: number) => `経過 ${s < 60 ? `${s} 秒` : `${Math.floor(s / 60)} 分 ${s % 60} 秒`}`,
    },
    fields: { summary: '要約', strengths: '強み', weaknesses: '弱み', fatalFlaws: '致命的な欠陥', comments: '詳細コメント', questions: '著者への質問', pathToAcceptance: '改善の道筋', overall: '総評' } as Record<string, string>,
    grounds: '判定根拠', groundsLead: '最終スコアはローカルの評価関数で計算しています。AI の評価は根拠の引用が本文で確認できた割合に応じて補正されます。',
    cols: { criterion: '観点', raw: 'AI 評価', verified: '根拠確認', adjusted: '補正後', weight: '重み', points: '寄与' },
    structureRow: (n: number, total: number) => `構成チェック（${n}/${total} 項目）`, subtotal: '小計', finalScore: '最終スコア',
    capUnsound: (adjusted: string) => `技術的妥当性が補正後 ${adjusted}（2 未満）のため 40 点が上限`, capFatal: '致命的な欠陥の指摘があるため 45 点が上限',
    band: (total: number, min: number, max: number | null, label: string) => `${total} 点は ${min}${max === null ? ' 点以上' : `〜${max - 1} 点`}の帯 → ${label}`,
    adjustNote: '根拠が本文で確認できない評価は、中立 (3) 側へ最大半分まで戻します（高評価・低評価とも同じ）。',
    confidenceWhy: (self: number, verified: number) => `AI の自己申告確信度 ${self}% × 引用確認による係数 ${verified}%`, truncatedNote: '先頭部分のみ評価したため ×0.85', ocrNote: 'OCR 主体の入力のため ×0.9',
    rationale: '評価理由', overall: '総評', comments: '詳細コメント', suggestion: '改善案', severity: { major: '重要', minor: '軽微' }, pathToAcceptance: '採択に近づけるために',
    history: '解析履歴', latest: '最新', historyNote: '再レビューしても以前の結果は履歴として残ります。',
    savedNote: '解析結果はこのブラウザーに保存され、tc-storage にも自動でバックアップされます。',
    toDark: 'ダークテーマに切り替え', toLight: 'ライトテーマに切り替え',
    tasks: { review: 'レビュー', study: '理解モード（未選択ならレビューと同じ）', ocr: 'OCR（画像のみのページ）' },
    study: {
      tab: '理解モード', reviewTab: 'レビュー',
      lead: '論文のストーリー（背景 → 問題 → 手法 → 結果 …）をノードグラフにします。質問するたびに答えが理解ツリーに箇条書きで積み上がり、読み進めるほど理解が深まります。',
      build: 'ストーリーを可視化する', building: 'ストーリーを組み立てています', rebuild: '作り直す', confirmRebuild: 'もう一度押すと作り直す（ツリーも消えます）',
      thinking: (chars: number) => `AI が考えています · ${chars.toLocaleString()} 文字受信`,
      ask: '質問する', askPlaceholder: 'わからないこと・もっと知りたいことを質問', askAbout: (label: string) => `「${label}」について質問（例: なぜそう言えるの？）`,
      selection: '選択箇所', explainSelection: 'この箇所をわかりやすく説明して',
      followUps: '次に聞くとよい質問', tree: '理解ツリー', thesis: 'この論文のストーリー',
      asked: (n: number) => `質問 ${n} 件`, questionBadge: 'この質問で追加',
      selectHint: 'テキストを選択すると質問に使えます', zoomIn: '拡大', zoomOut: '縮小',
      notReady: '本文のスキャンが終わると使えます。', copy: 'ノートをコピー',
      toGraph: 'グラフへ',
      afterBuild: 'ストーリーを可視化すると表示されます。',
      panels: { pdf: 'PDF', graph: 'ストーリー', focus: '選択中のノード', ask: '質問' },
      panelLabels: { collapse: '折りたたむ', expand: '開く', hide: 'パネルを隠す', maximize: '最大化（見出しのダブルクリックでも可）', restore: '元に戻す（Esc）', escHint: 'で元に戻す', dragHint: 'ドラッグで移動（上下に落とすと積む・左右の端に落とすと列を分ける）' },
      showPanel: 'パネルを表示', resetLayout: 'レイアウトを戻す', resetLayoutHint: 'パネルの配置と大きさを初期状態に戻す',
      language: '出力言語（グラフ・ツリー・回答）',
      langMismatch: (from: string, to: string) => `このノートは${from}で書かれています。これからの回答は${to}で追加されます。`,
      translate: (to: string) => `${to}に翻訳（ツリーはそのまま）`,
      kinds: { background: '背景', problem: '問題', gap: '未解決点', claim: '主張', method: '手法', experiment: '実験', result: '結果', limitation: '限界', implication: '意義', concept: '概念' } as Record<StoryKind, string>,
    },
    viewer: {
      pick: 'tc-pdf-viewer から選ぶ', title: 'tc-pdf-viewer の PDF', search: 'ファイル名で絞り込み', empty: 'tc-pdf-viewer に PDF がありません。',
      unknown: 'このサイトで tc-pdf-viewer がまだ使われていません。tc-pdf-viewer で PDF を追加すると、ここから選べます。', open: 'tc-pdf-viewer を開く',
      note: '選んだ PDF は TC Papers にコピーされ、理解モードで開きます（tc-pdf-viewer 側は変更しません）。',
    },
  },
  en: {
    drop: 'Drop PDFs here to add them', choose: 'Choose files', limit: 'Up to 50 MB per file',
    settings: 'Settings', close: 'Close', back: 'All papers',
    states: { queued: 'Queued', scanning: 'Scanning', scanned: 'Not reviewed', reviewing: 'Reviewing', done: 'Done', error: 'Error' },
    errors: {
      AI_NOT_CONFIGURED: 'No AI connection. Pick one in Settings and review resumes automatically.',
      NEEDS_OCR: 'This PDF has no text layer. Choose a vision-capable OCR model in Settings to scan it.',
      AI_NO_TEXT: 'No readable text was found.',
      OCR_FAILED: 'OCR failed. Choose an image-capable model for OCR in Settings and retry.',
      AI_INVALID_RESPONSE: 'Could not parse the AI response. Try again.',
      PDF_MISSING: 'The PDF file is missing. Drop it again.',
      PDF_READ_FAILED: 'Could not read this PDF. Check for corruption or password protection.',
      PDF_INVALID: 'Not a valid PDF.', PDF_TOO_LARGE: 'Larger than 50 MB.', PDF_STORAGE: 'Could not save to browser storage.',
      VIEWER_FILE_MISSING: 'Could not load this PDF from tc-pdf-viewer. Open it there once, then pick it again.',
      UNKNOWN: 'Processing failed.',
    } as Record<string, string>,
    decisions: { 'strong-accept': 'Strong Accept', accept: 'Accept', borderline: 'Borderline', 'weak-reject': 'Weak Reject', reject: 'Reject' } as Record<Decision, string>,
    criteria: { soundness: 'Soundness', evidence: 'Evidence', novelty: 'Novelty', significance: 'Significance', clarity: 'Clarity', reproducibility: 'Reproducibility' } as Record<CriterionId, string>,
    structureLabels: { abstract: 'Abstract', method: 'Method', results: 'Experiments/results', limitations: 'Limitations', references: 'References', artifacts: 'Code/data released' } as Record<string, string>,
    caps: { unsound: 'Capped at 40: low soundness', fatal: 'Capped at 45: fatal flaw' },
    score: 'Score', confidence: 'Confidence', weight: 'weight', evidence: 'Evidence', verified: 'found in paper', unverified: 'not found in paper',
    summary: 'Summary', strengths: 'Strengths', weaknesses: 'Weaknesses', questions: 'Questions for authors', fatalFlaws: 'Fatal flaws', structure: 'Structure check',
    howScored: 'How this is scored', formula: 'Each 1–5 criterion is pulled toward neutral (3) by the share of its quotes found in the paper → weighted mean mapped to 0–100 (90%) + structure check (10%) → caps for fatal flaws.',
    pages: (scan: { pages: number; scannedPages: number; ocrPages: number; truncated: boolean }) => `${scan.pages} pages` + (scan.truncated ? ` (first ${scan.scannedPages} reviewed)` : '') + (scan.ocrPages ? ` · OCR ${scan.ocrPages}` : ''),
    startReview: 'Start review', notReviewed: 'Not reviewed yet. You can also use it in understanding mode only.', rerun: 'Review again', retry: 'Retry', open: 'Open PDF', remove: 'Delete', confirmRemove: 'Click again to delete', copyMd: 'Copy Markdown', copied: 'Copied',
    duplicate: 'Already added', aiSettings: 'AI connection', aiNote: 'Choose models for Review and OCR. OCR needs an image-capable model. PDF text is sent to the selected AI.',
    steps: { scan: 'Scan text', review: 'AI review', score: 'Score' },
    progress: {
      queued: 'Waiting in line (one paper at a time)',
      scan: (done?: number, total?: number) => total ? `Extracting text from page ${done}/${total}` : 'Opening the PDF',
      ocr: (page?: number, total?: number) => `OCR on page ${page}/${total} (no text layer)`,
      send: (chars?: number) => `Sent ${(chars || 0).toLocaleString()} characters to the AI, waiting for a reply`,
      generate: (chars?: number, field?: string) => `AI is writing the review${field ? `: ${field}` : ''} · ${(chars || 0).toLocaleString()} characters received`,
      elapsed: (s: number) => `${s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`} elapsed`,
    },
    fields: { summary: 'summary', strengths: 'strengths', weaknesses: 'weaknesses', fatalFlaws: 'fatal flaws', comments: 'detailed comments', questions: 'questions', pathToAcceptance: 'path to acceptance', overall: 'overall assessment' } as Record<string, string>,
    grounds: 'Why this decision', groundsLead: 'The final score is computed locally. Each AI rating is adjusted by how much of its quoted evidence was found in the paper.',
    cols: { criterion: 'Criterion', raw: 'AI rating', verified: 'Evidence found', adjusted: 'Adjusted', weight: 'Weight', points: 'Points' },
    structureRow: (n: number, total: number) => `Structure check (${n}/${total})`, subtotal: 'Subtotal', finalScore: 'Final score',
    capUnsound: (adjusted: string) => `Capped at 40: adjusted soundness ${adjusted} is below 2`, capFatal: 'Capped at 45: a fatal flaw was reported',
    band: (total: number, min: number, max: number | null, label: string) => `${total} falls in the ${min}${max === null ? '+' : `–${max - 1}`} band → ${label}`,
    adjustNote: 'Ratings whose evidence is not found in the paper are pulled up to halfway back to neutral (3), for high and low ratings alike.',
    confidenceWhy: (self: number, verified: number) => `AI self-reported confidence ${self}% × evidence factor ${verified}%`, truncatedNote: 'only the beginning was reviewed ×0.85', ocrNote: 'mostly OCR input ×0.9',
    rationale: 'Rationale', overall: 'Overall assessment', comments: 'Detailed comments', suggestion: 'Suggestion', severity: { major: 'Major', minor: 'Minor' }, pathToAcceptance: 'Path to acceptance',
    history: 'Review history', latest: 'Latest', historyNote: 'Earlier results are kept when you review again.',
    savedNote: 'Results are saved in this browser and backed up to tc-storage automatically.',
    toDark: 'Switch to dark theme', toLight: 'Switch to light theme',
    tasks: { review: 'Review', study: 'Understanding mode (defaults to the review model)', ocr: 'OCR (image-only pages)' },
    study: {
      tab: 'Understand', reviewTab: 'Review',
      lead: 'Maps the story of the paper (background → problem → method → results …) as a node graph. Every question you ask adds its answer as bullets to your understanding tree, so it grows as you read.',
      build: 'Map the story', building: 'Building the story', rebuild: 'Rebuild', confirmRebuild: 'Click again to rebuild (clears the tree)',
      thinking: (chars: number) => `AI is thinking · ${chars.toLocaleString()} characters received`,
      ask: 'Ask', askPlaceholder: 'Ask about anything unclear or worth digging into', askAbout: (label: string) => `Ask about “${label}” (e.g. why does this hold?)`,
      selection: 'Selection', explainSelection: 'Explain this passage in plain terms',
      followUps: 'Good next questions', tree: 'Understanding tree', thesis: 'The story of this paper',
      asked: (n: number) => `${n} question${n === 1 ? '' : 's'}`, questionBadge: 'Added by',
      selectHint: 'Select text to ask about it', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
      notReady: 'Available once the text scan finishes.', copy: 'Copy notes',
      toGraph: 'Back to graph',
      afterBuild: 'Appears once the story is mapped.',
      panels: { pdf: 'PDF', graph: 'Story', focus: 'Selected node', ask: 'Ask' },
      panelLabels: { collapse: 'Collapse', expand: 'Expand', hide: 'Hide panel', maximize: 'Maximize (or double-click the header)', restore: 'Restore (Esc)', escHint: 'to restore', dragHint: 'Drag to move (drop on the top/bottom half to stack, on a left/right edge to split a column)' },
      showPanel: 'Show panel', resetLayout: 'Reset layout', resetLayoutHint: 'Restore the default panel arrangement and sizes',
      language: 'Output language (graph, tree, answers)',
      langMismatch: (from: string, to: string) => `These notes are in ${from}. New answers will be added in ${to}.`,
      translate: (to: string) => `Translate to ${to} (keeps the tree)`,
      kinds: { background: 'Background', problem: 'Problem', gap: 'Gap', claim: 'Claim', method: 'Method', experiment: 'Experiment', result: 'Result', limitation: 'Limitation', implication: 'Implication', concept: 'Concept' } as Record<StoryKind, string>,
    },
    viewer: {
      pick: 'Pick from tc-pdf-viewer', title: 'PDFs in tc-pdf-viewer', search: 'Filter by name', empty: 'No PDFs in tc-pdf-viewer yet.',
      unknown: 'tc-pdf-viewer has not been used on this site yet. Add PDFs there and they show up here.', open: 'Open tc-pdf-viewer',
      note: 'The PDF is copied into TC Papers and opens in understanding mode (tc-pdf-viewer is not changed).',
    },
  },
}
export type Copy = typeof COPY.ja
