import type { CriterionId } from './types'
import type { Decision } from './lib/score'

export type Locale = 'ja' | 'en'

export function detectLocale(): Locale {
  return typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('ja') ? 'ja' : 'en'
}

export const COPY = {
  ja: {
    drop: 'PDF をドロップすると自動でレビューします', choose: 'ファイルを選択', limit: '1 ファイル 50 MB まで',
    settings: '設定', close: '閉じる', back: '一覧へ',
    states: { queued: '待機中', scanning: 'スキャン中', reviewing: 'レビュー中', done: '完了', error: 'エラー' },
    errors: {
      AI_NOT_CONFIGURED: 'AI 未設定です。設定から接続先を選ぶと自動で再開します。',
      NEEDS_OCR: '画像のみの PDF です。設定で OCR 用の画像対応モデルを選ぶと再スキャンできます。',
      AI_NO_TEXT: '本文を読み取れませんでした。',
      OCR_FAILED: 'OCR に失敗しました。設定の OCR に画像入力対応モデルを選んで再試行してください。',
      AI_INVALID_RESPONSE: 'AI の応答を解釈できませんでした。再実行してください。',
      PDF_MISSING: 'PDF 本体が見つかりません。もう一度ドロップしてください。',
      PDF_READ_FAILED: 'PDF を読み込めません。破損やパスワード保護を確認してください。',
      PDF_INVALID: '有効な PDF ではありません。', PDF_TOO_LARGE: '50 MB を超えています。', PDF_STORAGE: 'ブラウザーに保存できませんでした。',
      UNKNOWN: '処理に失敗しました。',
    } as Record<string, string>,
    decisions: { 'strong-accept': 'Strong Accept', accept: 'Accept', borderline: 'Borderline', 'weak-reject': 'Weak Reject', reject: 'Reject' } as Record<Decision, string>,
    criteria: { soundness: '技術的妥当性', evidence: '実証の強さ', novelty: '新規性', significance: '重要性', clarity: '明瞭さ', reproducibility: '再現性' } as Record<CriterionId, string>,
    structureLabels: { abstract: '要旨', method: '手法', results: '実験・結果', limitations: '限界の議論', references: '参考文献', artifacts: 'コード/データ公開' } as Record<string, string>,
    caps: { unsound: '技術的妥当性が低いため上限 40', fatal: '致命的な欠陥があるため上限 45' },
    score: 'スコア', confidence: '信頼度', weight: '重み', evidence: '根拠', verified: '本文で確認', unverified: '本文に見当たらない',
    summary: '要約', strengths: '強み', weaknesses: '弱み', questions: '著者への質問', fatalFlaws: '致命的な欠陥', structure: '構成チェック',
    howScored: '算出方法', formula: '各観点 1–5 を根拠の確認率で中立 (3) 側へ補正 → 重み付き平均を 0–100 に換算 (90%) + 構成チェック (10%) → 致命的欠陥などで上限。',
    pages: (scan: { pages: number; scannedPages: number; ocrPages: number; truncated: boolean }) => `${scan.pages} ページ` + (scan.truncated ? `（先頭 ${scan.scannedPages} ページを評価）` : '') + (scan.ocrPages ? ` · OCR ${scan.ocrPages} ページ` : ''),
    rerun: '再レビュー', retry: '再試行', open: 'PDF を開く', remove: '削除', confirmRemove: 'もう一度押すと削除', copyMd: 'Markdown をコピー', copied: 'コピーしました',
    duplicate: '登録済みの PDF です', aiSettings: 'AI 接続', aiNote: '「レビュー」と「OCR」に使うモデルを選べます。OCR には画像入力に対応したモデルが必要です。PDF 本文は選択した AI に送信されます。',
    tasks: { review: 'レビュー', ocr: 'OCR（画像のみのページ）' },
    steps: { scan: '本文スキャン', review: 'AI 査読', score: '採点' },
    progress: {
      queued: '順番待ちです（1 本ずつ処理します）',
      scan: (done?: number, total?: number) => total ? `ページ ${done}/${total} のテキストを抽出中` : 'PDF を開いています',
      ocr: (page?: number, total?: number) => `ページ ${page}/${total} を OCR 中（文字情報のないページ）`,
      send: (chars?: number) => `本文 ${(chars || 0).toLocaleString()} 文字を AI に送信し、応答を待っています`,
      generate: (chars?: number, field?: string) => `AI が査読を執筆中${field ? `: ${field}` : ''} · ${(chars || 0).toLocaleString()} 文字受信`,
      elapsed: (s: number) => `経過 ${s < 60 ? `${s} 秒` : `${Math.floor(s / 60)} 分 ${s % 60} 秒`}`,
    },
    fields: { summary: '要約', strengths: '強み', weaknesses: '弱み', fatalFlaws: '致命的な欠陥', comments: '詳細コメント', questions: '著者への質問', pathToAcceptance: '改善の道筋', overall: '総評' } as Record<string, string>,
    grounds: '判定根拠', groundsLead: '最終スコアはローカルの評価関数で計算しています。AI の評価は根拠の引用が本文で確認できた割合に応じて補正されます。',
    cols: { criterion: '観点', raw: 'AI 評価', verified: '根拠確認', adjusted: '補正後', weight: '重み', points: '寄与' },
    structureRow: (n: number, total: number) => `構成チェック（${n}/${total} 項目）`, subtotal: '小計', finalScore: '最終スコア',
    capUnsound: (adjusted: string) => `技術的妥当性が補正後 ${adjusted}（2 未満）のため 40 点が上限`, capFatal: '致命的な欠陥の指摘があるため 45 点が上限',
    band: (total: number, min: number, max: number | null, label: string) => `${total} 点は ${min}${max === null ? ' 点以上' : `〜${max - 1} 点`}の帯 → ${label}`,
    adjustNote: '根拠が本文で確認できない評価は、中立 (3) 側へ最大半分まで戻します（高評価・低評価とも同じ）。',
    confidenceWhy: (self: number, verified: number) => `AI の自己申告確信度 ${self}% × 引用確認による係数 ${verified}%`, truncatedNote: '先頭部分のみ評価したため ×0.85', ocrNote: 'OCR 主体の入力のため ×0.9',
    rationale: '評価理由', overall: '総評', comments: '詳細コメント', suggestion: '改善案', severity: { major: '重要', minor: '軽微' }, pathToAcceptance: '採択に近づけるために',
    history: '解析履歴', latest: '最新', historyNote: '再レビューしても以前の結果は履歴として残ります。',
    savedNote: '解析結果はこのブラウザーに保存され、tc-storage にも自動でバックアップされます。',
    toDark: 'ダークテーマに切り替え', toLight: 'ライトテーマに切り替え',
  },
  en: {
    drop: 'Drop PDFs here to review them automatically', choose: 'Choose files', limit: 'Up to 50 MB per file',
    settings: 'Settings', close: 'Close', back: 'All papers',
    states: { queued: 'Queued', scanning: 'Scanning', reviewing: 'Reviewing', done: 'Done', error: 'Error' },
    errors: {
      AI_NOT_CONFIGURED: 'No AI connection. Pick one in Settings and review resumes automatically.',
      NEEDS_OCR: 'This PDF has no text layer. Choose a vision-capable OCR model in Settings to scan it.',
      AI_NO_TEXT: 'No readable text was found.',
      OCR_FAILED: 'OCR failed. Choose an image-capable model for OCR in Settings and retry.',
      AI_INVALID_RESPONSE: 'Could not parse the AI response. Try again.',
      PDF_MISSING: 'The PDF file is missing. Drop it again.',
      PDF_READ_FAILED: 'Could not read this PDF. Check for corruption or password protection.',
      PDF_INVALID: 'Not a valid PDF.', PDF_TOO_LARGE: 'Larger than 50 MB.', PDF_STORAGE: 'Could not save to browser storage.',
      UNKNOWN: 'Processing failed.',
    } as Record<string, string>,
    decisions: { 'strong-accept': 'Strong Accept', accept: 'Accept', borderline: 'Borderline', 'weak-reject': 'Weak Reject', reject: 'Reject' } as Record<Decision, string>,
    criteria: { soundness: 'Soundness', evidence: 'Evidence', novelty: 'Novelty', significance: 'Significance', clarity: 'Clarity', reproducibility: 'Reproducibility' } as Record<CriterionId, string>,
    structureLabels: { abstract: 'Abstract', method: 'Method', results: 'Experiments/results', limitations: 'Limitations', references: 'References', artifacts: 'Code/data released' } as Record<string, string>,
    caps: { unsound: 'Capped at 40: low soundness', fatal: 'Capped at 45: fatal flaw' },
    score: 'Score', confidence: 'Confidence', weight: 'weight', evidence: 'Evidence', verified: 'found in paper', unverified: 'not found in paper',
    summary: 'Summary', strengths: 'Strengths', weaknesses: 'Weaknesses', questions: 'Questions for authors', fatalFlaws: 'Fatal flaws', structure: 'Structure check',
    howScored: 'How this is scored', formula: 'Each 1–5 criterion is pulled toward neutral (3) by the share of its quotes found in the paper → weighted mean mapped to 0–100 (90%) + structure check (10%) → caps for fatal flaws.',
    pages: (scan: { pages: number; scannedPages: number; ocrPages: number; truncated: boolean }) => `${scan.pages} pages` + (scan.truncated ? ` (first ${scan.scannedPages} reviewed)` : '') + (scan.ocrPages ? ` · OCR ${scan.ocrPages}` : ''),
    rerun: 'Review again', retry: 'Retry', open: 'Open PDF', remove: 'Delete', confirmRemove: 'Click again to delete', copyMd: 'Copy Markdown', copied: 'Copied',
    duplicate: 'Already added', aiSettings: 'AI connection', aiNote: 'Choose models for Review and OCR. OCR needs an image-capable model. PDF text is sent to the selected AI.',
    tasks: { review: 'Review', ocr: 'OCR (image-only pages)' },
    steps: { scan: 'Scan text', review: 'AI review', score: 'Score' },
    progress: {
      queued: 'Waiting in line (one paper at a time)',
      scan: (done?: number, total?: number) => total ? `Extracting text from page ${done}/${total}` : 'Opening the PDF',
      ocr: (page?: number, total?: number) => `OCR on page ${page}/${total} (no text layer)`,
      send: (chars?: number) => `Sent ${(chars || 0).toLocaleString()} characters to the AI, waiting for a reply`,
      generate: (chars?: number, field?: string) => `AI is writing the review${field ? `: ${field}` : ''} · ${(chars || 0).toLocaleString()} characters received`,
      elapsed: (s: number) => `${s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`} elapsed`,
    },
    fields: { summary: 'summary', strengths: 'strengths', weaknesses: 'weaknesses', fatalFlaws: 'fatal flaws', comments: 'detailed comments', questions: 'questions', pathToAcceptance: 'path to acceptance', overall: 'overall assessment' } as Record<string, string>,
    grounds: 'Why this decision', groundsLead: 'The final score is computed locally. Each AI rating is adjusted by how much of its quoted evidence was found in the paper.',
    cols: { criterion: 'Criterion', raw: 'AI rating', verified: 'Evidence found', adjusted: 'Adjusted', weight: 'Weight', points: 'Points' },
    structureRow: (n: number, total: number) => `Structure check (${n}/${total})`, subtotal: 'Subtotal', finalScore: 'Final score',
    capUnsound: (adjusted: string) => `Capped at 40: adjusted soundness ${adjusted} is below 2`, capFatal: 'Capped at 45: a fatal flaw was reported',
    band: (total: number, min: number, max: number | null, label: string) => `${total} falls in the ${min}${max === null ? '+' : `–${max - 1}`} band → ${label}`,
    adjustNote: 'Ratings whose evidence is not found in the paper are pulled up to halfway back to neutral (3), for high and low ratings alike.',
    confidenceWhy: (self: number, verified: number) => `AI self-reported confidence ${self}% × evidence factor ${verified}%`, truncatedNote: 'only the beginning was reviewed ×0.85', ocrNote: 'mostly OCR input ×0.9',
    rationale: 'Rationale', overall: 'Overall assessment', comments: 'Detailed comments', suggestion: 'Suggestion', severity: { major: 'Major', minor: 'Minor' }, pathToAcceptance: 'Path to acceptance',
    history: 'Review history', latest: 'Latest', historyNote: 'Earlier results are kept when you review again.',
    savedNote: 'Results are saved in this browser and backed up to tc-storage automatically.',
    toDark: 'Switch to dark theme', toLight: 'Switch to light theme',
  },
}
export type Copy = typeof COPY.ja
